name: Bump Version on Merge

on:
  pull_request:
    types:
      - closed  # Запускаем при закрытии PR

permissions:
  contents: write  # Даем права на пуш изменений

jobs:
  bump-version:
    if: github.event.pull_request.merged == true  # Запускаем только если PR смержен
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install tomli_w

      - name: Bump version in pyproject.toml
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}  # Получаем заголовок PR
        run: python .github/scripts/bump_version.py

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "🔖 Bump version after PR: ${{ github.event.pull_request.title }}"
          git push origin main

      - name: Create tag
        run: |
          NEW_VERSION=$(sed -n 's/^version = "\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/p' pyproject.toml)
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
